CREATE TABLE IF NOT EXISTS preventivi ( 
    numeroOrdine INTEGER PRIMARY KEY AUTOINCREMENT,
    nomeCliente TEXT NOT NULL,
    cognomeCliente TEXT NOT NULL,
    nascitaCliente TEXT NOT NULL,
    codiceFiscale TEXT NOT NULL, 
    tipo TEXT NOT NULL,
    codice INTEGER NOT NULL,
    descrizione TEXT NOT NULL,
    unitaMisura TEXT NOT NULL,
    quantita REAL NOT NULL,
    prezzoUnitario REAL NOT NULL,
    prezzoTotale REAL NOT NULL,
    MRprezzoUnitario REAL NOT NULL,
    MRprezzoTotale REAL NOT NULL,
    MRricarico INTEGER NOT NULL,
    manoRprezzoUnitario REAL NOT NULL,
    manoRprezzoTotale REAL NOT NULL,
    manoRricarico REAL NOT NULL,
    PMprezzoUnitario REAL NOT NULL,
    PMprezzoTotale REAL NOT NULL,
    CMprezzoUnitario REAL NOT NULL,
    CMprezzoTotale REAL NOT NULL
);